### ISSUE TITLE
Ajout d'un hook qui lance un linter javascript

### ISSUE THREAD

**Issue by arizona-08** [Jonathan-08/MangAnnuaire#11]
Description :
Avant chaque commit, git devra exécuter un hook exécutant eslint (linter javascript) pour vérifier le code de chaque fichier .js.

Raison de la Suggestion :
Cette fonctionnalité pourra être utile pour avoir un code propre, homogène et qui respecte certaine convention.

Priorité :
Propriété urgente pour l'organisation de l'équipe

**Comment by Pyracantharia** [comment]
Bonne idée
