### ISSUE TITLE
Fonctionnalité classement

### ISSUE THREAD

**Issue by Pyracantharia** [Jonathan-08/MangAnnuaire#3]
Description :
Fonctionnalité classement

Raison de la Suggestion :
pour aider les user a choisir l'animé / manga en tendance

Avantages Anticipés :
rendre le site plus cool
Impact Potentiel :
positif
Étapes de Mise en Œuvre (si connues) :
je suggere un fichier rank.html
Ressources Nécessaires :
ide 

Échéance (si applicable) :
pas de date
Priorité :
haute

**Comment by arizona-08** [comment]
Je m'en occupe

**Comment by Jonathan-08** [comment]
Rank added
